export const childLocation = {
  puzzleAboutLoccation: {
    id: 1,
    puzzleText: ``,
    puzzleFilePath: `/locationChild/16.png`,
    video: '',
    description_text: ``,
    description_filePath: ``,
    answer: '',
    rightAnswer: ['дети', 'ребенок', 'младенец', 'новорожденый', 'младенцы'],
    done: false,
    last_description_text: `До 7-9 месяцев дети действительно способны одновременно дышать и глотать, 
  благодаря особенностям анатомии гортани. У младенцев в первые месяцы жизни гортань 
  расположена значительно выше, чем у взрослых, и лишь со временем опускается в своё нормальное 
  положение. Это позволяет новорождённым без труда глотать и одновременно дышать через нос. 
  Согласно статистическим данным GPS вашего телефона, именно в этом парке капитан часто проводит время 
  со своим ребёнком.`,
    last_description_filePath: `/locationChild/part-1.mp3`,
    clues: [
      {
        id: '1',
        used: false,
        text: '',
        filePath: '',
      },
      {
        id: '2',
        used: false,
        text: '',
        filePath: '',
      },
      {
        id: '3',
        used: false,
        text: '',
        filePath: '',
      },
    ],
  },
  qRCode: {
    filePath: `/locationChild/17.png`,
  },
  puzzlePrevMain: {
    id: 1,
    puzzleText: `Найдите конструкцию напоминающую Стоунхендж. Посчитайте столбы, сколько их`,
    puzzleFilePath: ``,
    video: '',
    description_text: ``,
    description_filePath: ``,
    answer: '',
    rightAnswer: ['8'],
    done: false,
    last_description_text: ``,
    last_description_filePath: ``,
    clues: [
      {
        id: '1',
        used: false,
        text: '',
        filePath: '',
      },
      {
        id: '2',
        used: false,
        text: '',
        filePath: '',
      },
      {
        id: '3',
        used: false,
        text: '',
        filePath: '',
      },
    ],
  },
  puzzleMain: [
    {
      id: 1,
      puzzleText: `Детское любопытство, вдохновение и азарт помогали нашим предкам совершать 
  удивительные открытие и создавать изобретения, которые значительно улучшили нашу жизнь. 
  Сложно представить человеческую жизнь без этих изобретений`,
      puzzleFilePath: `/locationChild/19.png`,
      video: '',
      description_text: ``,
      description_filePath: ``,
      answer: '',
      rightAnswer: ['1'],
      done: false,
      last_description_text: ``,
      last_description_filePath: ``,
      clues: [
        {
          id: '1',
          used: false,
          text: '',
          filePath: '/locationChild/20.png',
        },
        {
          id: '2',
          used: false,
          text: '',
          filePath: '/locationChild/21.png',
        },
        {
          id: '3',
          used: false,
          text: '',
          filePath: '/locationChild/22.png',
        },
      ],
    },
    {
      id: 2,
      puzzleText: ``,
      puzzleFilePath: `/locationChild/23.png`,
      video: '',
      description_text: ``,
      description_filePath: ``,
      answer: '',
      rightAnswer: ['1'],
      done: false,
      last_description_text: ``,
      last_description_filePath: ``,
      clues: [
        {
          id: '1',
          used: false,
          text: '',
          filePath: '/locationChild/24.png',
        },
        {
          id: '2',
          used: false,
          text: '',
          filePath: '/locationChild/25.png',
        },
        {
          id: '3',
          used: false,
          text: '',
          filePath: '',
        },
      ],
    },
    {
      id: 3,
      puzzleText: ``,
      puzzleFilePath: `/locationChild/26.png`,
      video: '',
      description_text: ``,
      description_filePath: ``,
      answer: '',
      rightAnswer: ['1'],
      done: false,
      last_description_text: ``,
      last_description_filePath: ``,
      clues: [
        {
          id: '1',
          used: false,
          text: '',
          filePath: '/locationChild/27.png',
        },
        {
          id: '2',
          used: false,
          text: '',
          filePath: '/locationChild/28.png',
        },
        {
          id: '3',
          used: false,
          text: '',
          filePath: '',
        },
      ],
    },
    {
      id: 4,
      puzzleText: ``,
      puzzleFilePath: `/locationChild/29.png`,
      video: '',
      description_text: ``,
      description_filePath: ``,
      answer: '',
      rightAnswer: ['1'],
      done: false,
      last_description_text: ``,
      last_description_filePath: ``,
      clues: [
        {
          id: '1',
          used: false,
          text: '',
          filePath: '/locationChild/30.png',
        },
        {
          id: '2',
          used: false,
          text: '',
          filePath: '/locationChild/31.png',
        },
        {
          id: '3',
          used: false,
          text: '',
          filePath: '',
        },
      ],
    },
    {
      id: 5,
      puzzleText: ``,
      puzzleFilePath: `/locationChild/32.png`,
      video: '',
      description_text: ``,
      description_filePath: ``,
      answer: '',
      rightAnswer: ['1'],
      done: false,
      last_description_text: ``,
      last_description_filePath: ``,
      clues: [
        {
          id: '1',
          used: false,
          text: '',
          filePath: '/locationChild/33.png',
        },
        {
          id: '2',
          used: false,
          text: '',
          filePath: '/locationChild/34.png',
        },
        {
          id: '3',
          used: false,
          text: '',
          filePath: '/locationChild/35.png',
        },
      ],
    },
    {
      id: 6,
      puzzleText: ``,
      puzzleFilePath: `/locationChild/36.png`,
      video: '',
      description_text: ``,
      description_filePath: ``,
      answer: '',
      rightAnswer: ['1'],
      done: false,
      last_description_text: `Поздравляем! Все слова отгаданы`,
      last_description_filePath: `/locationChild/part-2.mp3`,
      clues: [
        {
          id: '1',
          used: false,
          text: '',
          filePath: '/locationChild/37.png',
        },
        {
          id: '2',
          used: false,
          text: '',
          filePath: '/locationChild/38.png',
        },
        {
          id: '3',
          used: false,
          text: '',
          filePath: '',
        },
      ],
    },
  ],
};
