export const childLocation = {
  puzzleAboutLoccation: {
    id: 1,
    puzzleText: `Следующая локация связана с теми, кто,
     в отличие от нас, умеет дышать и глотать одновременно. Кто же это?`,
    puzzleFilePath: ``,
    video: '',
    discription_text: ``,
    discription_filePath: ``,
    answer: '',
    rightAnswer: ['дети', 'ребенок', 'младенец', 'новорожденый', 'младенцы'],
    done: false,
    last_discription_text: `До 7-9 месяцев дети действительно способны одновременно дышать и глотать, 
  благодаря особенностям анатомии гортани. У младенцев в первые месяцы жизни гортань 
  расположена значительно выше, чем у взрослых, и лишь со временем опускается в своё нормальное 
  положение. Это позволяет новорождённым без труда глотать и одновременно дышать через нос. 
  Согласно статистическим данным GPS вашего телефона, именно в этом парке капитан часто проводит время 
  со своим ребёнком.`,
    last_discription_filePath: `/locationChild/part-1.mp3`,
    clues: [
      {
        id: '1',
        used: false,
        text: '',
        filePath: '',
      },
      {
        id: '2',
        used: false,
        text: '',
        filePath: '',
      },
      {
        id: '3',
        used: false,
        text: '',
        filePath: '',
      },
    ],
  },
  QRCode: {
    filePath: ``,
  },
  puzzlePrevMain: {
    id: 1,
    puzzleText: `Найдите конструкцию напоминающую Стоунхендж. Посчитайте столбы, сколько их`,
    puzzleFilePath: ``,
    video: '',
    discription_text: ``,
    discription_filePath: ``,
    answer: '',
    rightAnswer: ['8'],
    done: false,
    last_discription_text: ``,
    last_discription_filePath: ``,
    clues: [
      {
        id: '1',
        used: false,
        text: '',
        filePath: '',
      },
      {
        id: '2',
        used: false,
        text: '',
        filePath: '',
      },
      {
        id: '3',
        used: false,
        text: '',
        filePath: '',
      },
    ],
  },
  puzzleMain: [
    {
      id: 1,
      puzzleText: `Детское любопытство, вдохновение и азарт помогали нашим предкам совершать 
  удивительные открытие и создавать изобретения, которые значительно улучшили нашу жизнь. 
  Сложно представить человеческую жизнь без этих изобретений`,
      puzzleFilePath: ``,
      video: '',
      discription_text: ``,
      discription_filePath: ``,
      answer: '',
      rightAnswer: ['', ''],
      done: false,
      last_discription_text: ``,
      last_discription_filePath: ``,
      clues: [
        {
          id: '1',
          used: false,
          text: '',
          filePath: '',
        },
        {
          id: '2',
          used: false,
          text: '',
          filePath: '',
        },
        {
          id: '3',
          used: false,
          text: '',
          filePath: '',
        },
      ],
    },
    {
      id: 2,
      puzzleText: ``,
      puzzleFilePath: ``,
      video: '',
      discription_text: ``,
      discription_filePath: ``,
      answer: '',
      rightAnswer: ['', ''],
      done: false,
      last_discription_text: ``,
      last_discription_filePath: ``,
      clues: [
        {
          id: '1',
          used: false,
          text: '',
          filePath: '',
        },
        {
          id: '2',
          used: false,
          text: '',
          filePath: '',
        },
        {
          id: '3',
          used: false,
          text: '',
          filePath: '',
        },
      ],
    },
    {
      id: 3,
      puzzleText: ``,
      puzzleFilePath: ``,
      video: '',
      discription_text: ``,
      discription_filePath: ``,
      answer: '',
      rightAnswer: ['', ''],
      done: false,
      last_discription_text: ``,
      last_discription_filePath: ``,
      clues: [
        {
          id: '1',
          used: false,
          text: '',
          filePath: '',
        },
        {
          id: '2',
          used: false,
          text: '',
          filePath: '',
        },
        {
          id: '3',
          used: false,
          text: '',
          filePath: '',
        },
      ],
    },
    {
      id: 4,
      puzzleText: ``,
      puzzleFilePath: ``,
      video: '',
      discription_text: ``,
      discription_filePath: ``,
      answer: '',
      rightAnswer: ['', ''],
      done: false,
      last_discription_text: ``,
      last_discription_filePath: ``,
      clues: [
        {
          id: '1',
          used: false,
          text: '',
          filePath: '',
        },
        {
          id: '2',
          used: false,
          text: '',
          filePath: '',
        },
        {
          id: '3',
          used: false,
          text: '',
          filePath: '',
        },
      ],
    },
    {
      id: 5,
      puzzleText: ``,
      puzzleFilePath: ``,
      video: '',
      discription_text: ``,
      discription_filePath: ``,
      answer: '',
      rightAnswer: ['', ''],
      done: false,
      last_discription_text: ``,
      last_discription_filePath: ``,
      clues: [
        {
          id: '1',
          used: false,
          text: '',
          filePath: '',
        },
        {
          id: '2',
          used: false,
          text: '',
          filePath: '',
        },
        {
          id: '3',
          used: false,
          text: '',
          filePath: '',
        },
      ],
    },
    {
      id: 6,
      puzzleText: ``,
      puzzleFilePath: ``,
      video: '',
      discription_text: ``,
      discription_filePath: ``,
      answer: '',
      rightAnswer: ['', ''],
      done: false,
      last_discription_text: `Поздравляем! Все слова отгаданы`,
      last_discription_filePath: ``,
      clues: [
        {
          id: '1',
          used: false,
          text: '',
          filePath: '',
        },
        {
          id: '2',
          used: false,
          text: '',
          filePath: '',
        },
        {
          id: '3',
          used: false,
          text: '',
          filePath: '',
        },
      ],
    },
  ],
};
