export const homeLocationData = {
  puzzleAboutLoccation: {
    id: 1,
    puzzleText: `Под влиянием легенд о происхождении нечистой силы ЕГО называли падшим ангелом, которого Бог в наказание сбросил на землю. Обычно ИМ считался умерший член семьи, первопредок рода; умерший член семьи, который за грехи назначен Богом в услужение живым родственникам. Кто ОН?`,
    puzzleFilePath: '',
    video: '',
    description_text: ``,
    description_filePath: ``,
    answer: '',
    rightAnswer: ['Домовой'],
    done: false,
    last_description_text: `Домовой, согласно народным преданиям, обитает в жилище, охраняя его обитателей. Люди сохраняют веру в его присутствие, хотя искусственный интеллект может иметь собственное мнение по этому поводу. Однако, давайте избегать споров на эту тему. Пожалуйста, отправляйтесь в место, где капитан вашей команды ощущает наибольший уют и безопасность.`,
    last_description_filePath: `/locationHome/part-1.mp3`,
    clues: [
      {
        id: '1',
        used: false,
        text: 'Напоминаю: в ваших руках находится телефон, обладающий доступом к мировой паутине.',
        filePath: '',
      },
      {
        id: '2',
        used: false,
        text: 'Где обычно проживают ваши близкие родственники?',
        filePath: '',
      },
      {
        id: '3',
        used: false,
        text: 'Кузя, персонаж из детского анимационного сериала.',
        filePath: '',
      },
    ],
  },
  qRCode: {
    filePath: `/locationHome/3.png`,
  },
  puzzlePrevMain: {
    id: 1,
    puzzleText: `Судя по данным службы, которая заботится о вашем "внутреннем мире", на территории вашего дома расположен необычный "портал", обещающий вам взглянуть в мир неисповедимых тайн и захватывающих приключений. На его входе изображено название. Какое?`,
    puzzleFilePath: '',
    video: '',
    description_text: ``,
    description_filePath: ``,
    answer: '',
    rightAnswer: ['innoflow', 'inno flow'],
    done: false,
    last_description_text: `Поздравляем! Вы достигли первой локации. Это дом, в котором проживает ваш капитан. Чтобы превзойти искусственный интеллект, важно понять ключевые различия между искусственным интеллектом и живым человеком. Попробуйте определить, в чем именно человек непременно превосходит искусственный интеллект.`,
    last_description_filePath: `/locationHome/part-2.mp3`,
    clues: [
      {
        id: '1',
        used: false,
        text: '"порталов" 6',
        filePath: '',
      },
      {
        id: '2',
        used: false,
        text: 'вход у "портала" зеленый',
        filePath: '',
      },
    ],
  },
  puzzleMain: {
    id: 1,
    puzzleText: ``,
    puzzleFilePath: '/locationHome/5.png',
    video: '',
    description_text: ``,
    description_filePath: ``,
    answer: '',
    rightAnswer: ['САМОСОЗНАНИЕ'],
    done: false,
    last_description_text: `Самосознание и осознание себя как личности связаны с определенными аспектами, такими как эмоции, интуиция, творчество, способность к самопознанию и критическому мышлению, которые до сих пор не могут быть полностью воссозданы в искусственном интеллекте.`,
    last_description_filePath: `/locationHome/part-3.mp3`,
    clues: [
      {
        id: '1',
        used: false,
        text: ``,
        filePath: '/locationHome/6.png',
      },
      {
        id: '2',
        used: false,
        text: ``,
        filePath: '/locationHome/7.png',
      },
      {
        id: '3',
        used: false,
        text: '',
        filePath: '/locationHome/8.png',
      },
    ],
  },
};
