export const lastLoccation = {
  puzzleAboutLoccation: [
    {
      id: 1,
      puzzleText: ``,
      puzzleFilePath: ``,
      video: "",
      discription_text: ``,
      discription_filePath: ``,
      answer: "",
      rightAnswer: ["Александр Пушкин"],
      done: false,
      last_description_text: ``,
      last_description_filePath: ``,
      clues: [
        {
          id: "1",
          used: false,
          text: "",
          filePath: "",
        },
        {
          id: "2",
          used: false,
          text: "",
          filePath: "",
        },
        {
          id: "3",
          used: false,
          text: "",
          filePath: "",
        },
      ],
    },
    {
      id: 2,
      puzzleText: ``,
      puzzleFilePath: ``,
      video: "",
      discription_text: ``,
      discription_filePath: ``,
      answer: "",
      rightAnswer: ["Виктор Цой "],
      done: false,
      last_description_text: ``,
      last_description_filePath: ``,
      clues: [
        {
          id: "1",
          used: false,
          text: "",
          filePath: "",
        },
        {
          id: "2",
          used: false,
          text: "",
          filePath: "",
        },
        {
          id: "3",
          used: false,
          text: "",
          filePath: "",
        },
      ],
    },
    {
      id: 3,
      puzzleText: ``,
      puzzleFilePath: ``,
      video: "",
      discription_text: ``,
      discription_filePath: ``,
      answer: "",
      rightAnswer: ["Михаил Лермонтов"],
      done: false,
      last_description_text: ``,
      last_description_filePath: ``,
      clues: [
        {
          id: "1",
          used: false,
          text: "",
          filePath: "",
        },
        {
          id: "2",
          used: false,
          text: "",
          filePath: "",
        },
        {
          id: "3",
          used: false,
          text: "",
          filePath: "",
        },
      ],
    },
    {
      id: 4,
      puzzleText: ``,
      puzzleFilePath: ``,
      video: "",
      discription_text: ``,
      discription_filePath: ``,
      answer: "",
      rightAnswer: ["Иванушки International "],
      done: false,
      last_description_text: ``,
      last_description_filePath: ``,
      clues: [
        {
          id: "1",
          used: false,
          text: "",
          filePath: "",
        },
        {
          id: "2",
          used: false,
          text: "",
          filePath: "",
        },
        {
          id: "3",
          used: false,
          text: "",
          filePath: "",
        },
      ],
    },
    {
      id: 5,
      puzzleText: ``,
      puzzleFilePath: ``,
      video: "",
      discription_text: ``,
      discription_filePath: ``,
      answer: "",
      rightAnswer: ["Иван Андреевич Крылов "],
      done: false,
      last_description_text: `Поздравляем, вы справились с последним заданием! Пока ещё ни одна команда не успела его выполнить! Также, вы выполнили все пять заданий использовав меньшее количество подсказок, чем остальные группы. Это значит, что у вашей команды есть шанс победить и спасти человечество от порабощения искусственным интеллектом. 
        Отправляйтесь на точку и авторизуйтесь раньше остальных, чтоб завершить квест победителями!
        `,
      last_description_filePath: `/locationLast/part-1.mp3`,
      clues: [
        {
          id: "1",
          used: false,
          text: "",
          filePath: "",
        },
        {
          id: "2",
          used: false,
          text: "",
          filePath: "",
        },
        {
          id: "3",
          used: false,
          text: "",
          filePath: "",
        },
      ],
    },
  ],
  QRCode: {
    filePath: ``,
  },
  puzzlePrevMain: {
    id: 1,
    puzzleText: `Поздравляем! Все загадки отгаданы. Вы победили! 
    Искусственный интеллект отступил и уступил власть человечеству. 
    Вы заслужили приз! зайдите во внутрь и закажите свое любимое блюдо`,
    puzzleFilePath: ``,
    video: "",
    discription_text: ``,
    discription_filePath: ``,
    answer: "",
    rightAnswer: ["", ""],
    done: false,
    last_discription_text: ``,
    last_discription_filePath: ``,
    clues: [
      {
        id: "1",
        used: false,
        text: "",
        filePath: "",
      },
      {
        id: "2",
        used: false,
        text: "",
        filePath: "",
      },
      {
        id: "3",
        used: false,
        text: "",
        filePath: "",
      },
    ],
  },
  puzzleMain: {
    id: 1,
    puzzleText: ``,
    puzzleFilePath: ``,
    video: "",
    discription_text: ``,
    discription_filePath: ``,
    answer: "",
    rightAnswer: ["", ""],
    done: false,
    last_discription_text: ``,
    last_discription_filePath: ``,
    clues: [
      {
        id: "1",
        used: false,
        text: "",
        filePath: "",
      },
      {
        id: "2",
        used: false,
        text: "",
        filePath: "",
      },
      {
        id: "3",
        used: false,
        text: "",
        filePath: "",
      },
    ],
  },
};
