export const lastLoccation = {
  puzzleAboutLoccation: [
    {
      id: 1,
      puzzleText: `Искусственный интеллект шагнул далеко за границы решения запутанных задач, обретя способность к творчеству. Предлагаем вам уникальный вызов: попробуйте угадать авторов или исполнителей пяти различных произведений, стихов и песен, которые были трансформированы искусственным интеллектом, придав им новое звучание.`,
      puzzleFilePath: `/locationLast/53.png`,
      video: "",
      description_text: ``,
      description_filePath: ``,
      answer: "",
      rightAnswer: ["Александр Пушкин", "Пушкин"],
      done: false,
      last_description_text: ``,
      last_description_filePath: ``,
      clues: [
        {
          id: "1",
          used: false,
          text: "Значит, классика для нас уже что-то вроде далёкого забытого родственника, о существовании которого мы вспоминаем раз в пятилетку.",
          filePath: "",
        },
        {
          id: "2",
          used: false,
          text: "Похоже, ваша учительница по литературе в очередной раз испытывает глубокое разочарование... Ну что ж, некоторые традиции просто неизменны.",
          filePath: "",
        },
      ],
    },
    {
      id: 2,
      puzzleText: ``,
      puzzleFilePath: `/locationLast/54.png`,
      video: "",
      description_text: ``,
      description_filePath: ``,
      answer: "",
      rightAnswer: ["Виктор Цой", "Цой"],
      done: false,
      last_description_text: ``,
      last_description_filePath: ``,
      clues: [
        {
          id: "1",
          used: false,
          text: "Кажется, эту песню уже перепели все, кто только мог, кроме самых ленивых. И у тех, возможно, просто не нашлось гитары.",
          filePath: "",
        },
      ],
    },
    {
      id: 3,
      puzzleText: ``,
      puzzleFilePath: `/locationLast/55.png`,
      video: "",
      description_text: ``,
      description_filePath: ``,
      answer: "",
      rightAnswer: ["Михаил Лермонтов", "Лермонтов", "Лермантов"],
      done: false,
      last_description_text: ``,
      last_description_filePath: ``,
      clues: [
        {
          id: "1",
          used: false,
          text: "Когда обстоятельства не в нашу пользу, остается лишь взяться за руль собственного воображения и направить его к новым горизонтам.",
          filePath: "",
        },
        {
          id: "2",
          used: false,
          text: "Так и быть, признаем: это тоже было в списке школьных уроков",
          filePath: "",
        },
      ],
    },
    {
      id: 4,
      puzzleText: ``,
      puzzleFilePath: `/locationLast/56.png`,
      video: "",
      description_text: ``,
      description_filePath: ``,
      answer: "",
      rightAnswer: ["Иванушки International", "Иванушки"],
      done: false,
      last_description_text: ``,
      last_description_filePath: ``,
      clues: [
        {
          id: "1",
          used: false,
          text: "ла ла ла ла ла ла ",
          filePath: "",
        },
        {
          id: "2",
          used: false,
          text: "ту ту туту ту",
          filePath: "",
        },
        {
          id: "3",
          used: false,
          text: "Подпевайте! не надо стесняться",
          filePath: "",
        },
      ],
    },
    {
      id: 5,
      puzzleText: ``,
      puzzleFilePath: `/locationLast/57.png`,
      video: "",
      description_text: ``,
      description_filePath: ``,
      answer: "",
      rightAnswer: ["Иван Андреевич Крылов", "Крылов"],
      done: false,
      last_description_text: `Поздравляем, вы справились с последним заданием! Пока ещё ни одна команда не успела его выполнить! Также, вы выполнили все пять заданий использовав меньшее количество подсказок, чем остальные группы. Это значит, что у вашей команды есть шанс победить и спасти человечество от порабощения искусственным интеллектом. 
        Отправляйтесь на точку и авторизуйтесь раньше остальных, чтоб завершить квест победителями!
        `,
      last_description_filePath: `/locationLast/part-1.mp3`,
      clues: [
        {
          id: "1",
          used: false,
          text: "Важным моментом является то, что эти предметы не приносят никакой пользы существу, хотя оно пытается играться с ними.",
          filePath: "",
        },
        {
          id: "2",
          used: false,
          text: "Фамилия автора намекает на его возможную способность к полету ",
          filePath: "",
        },
      ],
    },
  ],
  qRCode: {
    filePath: `/locationLast/59.png`,
  },
  puzzlePrevMain: {
    id: 1,
    puzzleText: `Поздравляем! Все загадки отгаданы. Вы победили! 
    Искусственный интеллект отступил и уступил власть человечеству. 
    Вы заслужили приз! зайдите во внутрь и закажите свое любимое блюдо`,
    puzzleFilePath: ``,
    video: "",
    description_text: ``,
    description_filePath: ``,
    answer: "",
    rightAnswer: ["1"],
    done: false,
    last_description_text: ``,
    last_description_filePath: ``,
    clues: [
      {
        id: "1",
        used: false,
        text: "",
        filePath: "",
      },
      {
        id: "2",
        used: false,
        text: "",
        filePath: "",
      },
      {
        id: "3",
        used: false,
        text: "",
        filePath: "",
      },
    ],
  },
  puzzleMain: {
    id: 1,
    puzzleText: ``,
    puzzleFilePath: ``,
    video: "",
    description_text: ``,
    description_filePath: ``,
    answer: "",
    rightAnswer: ["1"],
    done: false,
    last_description_text: ``,
    last_description_filePath: ``,
    clues: [
      {
        id: "1",
        used: false,
        text: "",
        filePath: "",
      },
      {
        id: "2",
        used: false,
        text: "",
        filePath: "",
      },
      {
        id: "3",
        used: false,
        text: "",
        filePath: "",
      },
    ],
  },
};
