export const templateLoccation = {
  puzzleAboutLoccation: {
    id: 1,
    puzzleText: ``,
    puzzleFilePath: ``,
    video: '',
    discription_text: ``,
    discription_filePath: ``,
    answer: '',
    rightAnswer: [''],
    done: false,
    last_discription_text: ``,
    last_discription_filePath: ``,
    clues: [
      {
        id: '1',
        used: false,
        text: '',
        filePath: '',
      },
      {
        id: '2',
        used: false,
        text: '',
        filePath: '',
      },
      {
        id: '3',
        used: false,
        text: '',
        filePath: '',
      },
    ],
  },
  QRCode: {
    filePath: ``,
  },
  puzzlePrevMain: {
    id: 1,
    puzzleText: ``,
    puzzleFilePath: ``,
    video: '',
    discription_text: ``,
    discription_filePath: ``,
    answer: '',
    rightAnswer: ['', ''],
    done: false,
    last_discription_text: ``,
    last_discription_filePath: ``,
    clues: [
      {
        id: '1',
        used: false,
        text: '',
        filePath: '',
      },
      {
        id: '2',
        used: false,
        text: '',
        filePath: '',
      },
      {
        id: '3',
        used: false,
        text: '',
        filePath: '',
      },
    ],
  },
  puzzleMain: {
    id: 1,
    puzzleText: ``,
    puzzleFilePath: ``,
    video: '',
    discription_text: ``,
    discription_filePath: ``,
    answer: '',
    rightAnswer: ['', ''],
    done: false,
    last_discription_text: ``,
    last_discription_filePath: ``,
    clues: [
      {
        id: '1',
        used: false,
        text: '',
        filePath: '',
      },
      {
        id: '2',
        used: false,
        text: '',
        filePath: '',
      },
      {
        id: '3',
        used: false,
        text: '',
        filePath: '',
      },
    ],
  },
};
